// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// i = 1, j = 2

// build the fibonacci sequence using a looping method - from https://www.thepolyglotdeveloper.com/2015/01/fibonacci-sequence-printed-javascript/

const limit = 4000000 // we're finding the sum of numbers in the fibonacci series which do not exceed four million

var looping = function(n) { // n is the nth number of the fibonacci series. In this formulation we have to establish where the 4m point is hit

  var sum = 0, a = 0, b = 1, f = 1;

  for(var i = 2; i <= n; i++) {

    f = a + b;

    if (f > limit) { // breaks the loop if the value of the current number from the fibonacci sequence exceeds the limit value we've been given. Lets us find an answer just by entering any sufficiently large value of n
      break
    } else {
      f % 2 === 0 ? sum += f : null // if f is even, add it to our running total
    }

    a = b;
    b = f;

    }
  return sum

}

console.log(looping(33)) // <--- 4613732
// the 33rd number of the fibonacci sequence is the last which does not exceed four million

// build the fibonacci sequence using a recursive method, also from the link above

// var recursive = function(n) {
//     if(n <= 2) {
//         return 1;
//     } else {
//         return this.recursive(n - 1) + this.recursive(n - 2);
//     }
// };
