// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// i = 1, j = 2

const limit = 20

// build the fibonacci sequence using looping method - from https://www.thepolyglotdeveloper.com/2015/01/fibonacci-sequence-printed-javascript/

var looping = function(n) {
    var a = 0, b = 1, f = 1;
    for(var i = 2; i <= n; i++) {
        f = a + b;
        a = b;
        b = f;

      // ternary only
      var loopingFibonacci = f % 2 === 0 ? loopingFibonacci + f : loopingFibonacci

    }
    // return the sum of even numbers of the fibonacci sequence up to limit n
    return loopingFibonacci;
};



// build the fibonacci sequence using a recursive method, also from the link above

var recursive = function(n) {
    if(n <= 2) {
        return 1;
    } else {
        return this.recursive(n - 1) + this.recursive(n - 2);
    }
};
